<?php
echo '';
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Fun Olympic</title>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta http-equiv="X-UA-Compatible" content="ie=edge">';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<link rel="stylesheet" href="css/ie.css">';
echo '<script src="js/jquery-1.7.1.min.js"></script>';
echo '<script src="js/superfish.js"></script>';
echo '<script src="js/jquery.easing.1.3.js"></script>';
echo '<script src="js/tms-0.4.1.js"></script>';
echo '<script src="js/slider.js"></script>';
echo '<!--[if lt IE 9]>';
echo '<script src="js/html5.js"></script>';
echo '<link rel="stylesheet" href="css/ie.css">';
echo '<![endif]-->';
echo '</head>';
echo '<body>';
echo '<div class="main-indents">';
echo '<div class="main">';
echo '<!-- Header -->';
echo '<header>';
echo '<h1 class="logo"><a href="index.html">Fun olympic</a></h1>';
echo '<nav>';
echo '<ul class="sf-menu">';
echo '';
echo '<li><a href="about.html">About</a></li>';
echo '<li> <a href="Live Streaming.html">Live Streaaming</a>';
echo '<ul>';
echo '<li><a href="Live Streaming.html">Football</a></li>';
echo '<li><a href="Live Streaming.html">Basket Ball</a></li>';
echo '<li> <a href="Live Streaming.html">Circket</a></li>';
echo '<li><a href="Live Streaming.html">Cycling</a></li>';
echo '<li><a href="Live Streaming.html">More Games</a></li>';
echo '</ul>';
echo '</li>';
echo '<li><a href="Blog.html">Blog</a></li>';
echo '<li><a href="gallery.html">Galarry</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '<li><a href="login.html">Signup/login</a>';
echo '<ul>';
echo '<li><a href="adminlogin.html">Admin Login</a></li>';
echo '<li><a href="normaluser.html">User Login</a></li>';
echo '</ul>';
echo '</li>';
echo '</ul>';
echo '</nav>';
echo '<div class="clear"></div>';
echo '</header>';
echo '<!-- Slider -->';
echo '<div class="mp-slider">';
echo '<ul class="items">';
echo '<li><img src="images/slide-1.jpg" alt="">';
echo '<div class="banner"><span class="row-1"><b>Stadium</b></span><span class="row-2"></span></div>';
echo '</li>';
echo '<li><img src="images/slide-2.jpg" alt="">';
echo '<div class="banner"><span class="row-1"><b>Bolt</b></span><span class="row-2"></b></span></div>';
echo '</li>';
echo '<li><img src="images/slide-3.jpg" alt="">';
echo '<div class="banner"><span class="row-1"><b>Cycling</b></span><span class="row-2"></span></div>';
echo '</li>';
echo '</ul>';
echo '<a href="#" class="mp-prev"></a> <a href="#" class="mp-next"></a> </div>';
echo '<!---content-->';
echo '<section class="about-us">';
echo '<div class="about">';
echo '<img src="images/pic.jpeg" class="pic">';
echo '<div class="text">';
echo '<h2>About Us</h2><p>';
echo '<h3>Fun Olympic</h3>';
echo '<p>The City of Yokyo won the bid to host the next FunOlympic Games in 2023. During the build-up to the planned games in 2023, the city had invested hugely in IT infrastructure and systems to make sure that the games would have been well organised, staffed, attended, and accessible to everyone.';
echo 'The FunOlympic committee have decided that they require a number of additional projects which';
echo 'need to be completed before the games start to ensure the games run smoothly and also that';
echo 'worldwide audiences can enjoy the games online</p>';
echo '<div class="data">';
echo '<a href="contact.html" class="hire">Contact Us</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '</body>';
echo '</html>';
echo '<!-- Footer -->';
echo '<footer>';
echo '<div class="copyright"> designed by saroj dhakal<a target="_blank" href="#/"></a> </div>';
echo '<ul class="social-list">';
echo '<li><a href="#"><img src="images/soc-icon-1.png" alt=""></a></li>';
echo '<li><a href="#"><img src="images/soc-icon-2.png" alt=""></a></li>';
echo '<li><a href="#"><img src="images/soc-icon-3.png" alt=""></a></li>';
echo '</ul>';
echo '</footer>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>