<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Fun Olympic</title>';
echo '<meta charset="utf-8">';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<script src="js/jquery-1.7.1.min.js"></script>';
echo '<script src="js/superfish.js"></script>';
echo '<script src="js/jquery.easing.1.3.js"></script>';
echo '<script src="js/tms-0.4.1.js"></script>';
echo '<script src="js/slider.js"></script>';
echo '<!--[if lt IE 9]>';
echo '<script src="js/html5.js"></script>';
echo '<link rel="stylesheet" href="css/ie.css">';
echo '<![endif]-->';
echo '</head>';
echo '<body>';
echo '<div class="main-indents">';
echo '<div class="main">';
echo '<!-- Header -->';
echo '<header>';
echo '<h1 class="logo"><a href="index.html">Fun olympic</a></h1>';
echo '<nav>';
echo '<ul class="sf-menu">';
echo '';
echo '<li><a href="about.html">About</a></li>';
echo '<li> <a href="Live Streaming.html">Live Streaaming</a>';
echo '<ul>';
echo '<li><a href="Live Streaming.html">Football</a></li>';
echo '<li><a href="Live Streaming.html">Basket Ball</a></li>';
echo '<li> <a href="Live Streaming.html">Circket</a></li>';
echo '<li><a href="Live Streaming.html">Cycling</a></li>';
echo '<li><a href="Live Streaming.html">More Games</a></li>';
echo '</ul>';
echo '</li>';
echo '<li><a href="Blog.html">Blog</a></li>';
echo '<li><a href="gallery.html">Galarry</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '<li><a href="register.php">Signup/login</a>';
echo '<ul>';
echo '<li><a href="login.php">Admin Login</a></li>';
echo '<li><a href="login.php">User Login</a></li>';
echo '</ul>';
echo '</li>';
echo '</ul>';
echo '</nav>';
echo '<div class="clear"></div>';
echo '</header>';
echo '<!-- Slider -->';
echo '<div class="mp-slider">';
echo '<ul class="items">';
echo '<li><img src="images/slide-1.jpg" alt="">';
echo '<div class="banner"><span class="row-1"><b>Stadium</b></span><span class="row-2"></span></div>';
echo '</li>';
echo '<li><img src="images/slide-2.jpg" alt="">';
echo '<div class="banner"><span class="row-1"><b>Bolt</b></span><span class="row-2"></b></span></div>';
echo '</li>';
echo '<li><img src="images/slide-3.jpg" alt="">';
echo '<div class="banner"><span class="row-1"><b>Cycling</b></span><span class="row-2"></span></div>';
echo '</li>';
echo '</ul>';
echo '<a href="#" class="mp-prev"></a> <a href="#" class="mp-next"></a> </div>';
echo '<!-- Content -->';
echo '<section id="content">';
echo '<div class="container_12">';
echo '<article class="a1">';
echo '<div class="wrapper"> <img src="images/page1-img1.png" alt="" class="img-indent">';
echo '<div class="extra-wrap">';
echo '<h3> <span class="welcome">Welcome</span> To Fun Olympics </h3>';
echo '<p class="p1">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod';
echo 'tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,';
echo 'quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo';
echo 'consequat.</p>';
echo '</div>';
echo '</div>';
echo '</article>';
echo '<article class="content-box">';
echo '<h3 class="hp-1">Upcoming Events:</h3>';
echo '<div class="wrapper">';
echo '<div class="col-1">';
echo '<figure class="img-box"> <img src="images/page1-img2.jpg" alt=""> </figure>';
echo '<h5><span>31</span> june</h5>';
echo '<p>Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna. </p>';
echo '</div>';
echo '<div class="col-1">';
echo '<figure class="img-box"> <img src="images/page1-img3.jpg" alt=""> </figure>';
echo '<h5><span>21</span> july</h5>';
echo '<p> Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna. </p>';
echo '</div>';
echo '<div class="col-2">';
echo '<figure class="img-box"> <img src="images/page1-img4.jpg" alt=""> </figure>';
echo '<h5><span>03</span> August</h5>';
echo '<p> Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna.';
echo '</div>';
echo '<div class="col-1">';
echo '<figure class="img-box"> <img src="images/page1-img2.jpg" alt=""> </figure>';
echo '<h5><span>31</span> june</h5>';
echo '<p>Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna. </p>';
echo '</div>';
echo '<div class="col-1">';
echo '<figure class="img-box"> <img src="images/page1-img3.jpg" alt=""> </figure>';
echo '<h5><span>21</span> july</h5>';
echo '<p> Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna. </p>';
echo '</div>';
echo '<div class="col-2">';
echo '<figure class="img-box"> <img src="images/page1-img4.jpg" alt=""> </figure>';
echo '<h5><span>03</span> August</h5>';
echo '<p> Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna.';
echo '</div>';
echo '<div class="col-1">';
echo '<figure class="img-box"> <img src="images/page1-img2.jpg" alt=""> </figure>';
echo '<h5><span>31</span> june</h5>';
echo '<p>Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna. </p>';
echo '</div>';
echo '<div class="col-1">';
echo '<figure class="img-box"> <img src="images/page1-img3.jpg" alt=""> </figure>';
echo '<h5><span>21</span> july</h5>';
echo '<p> Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna. </p>';
echo '</div>';
echo '<div class="col-2">';
echo '<figure class="img-box"> <img src="images/page1-img4.jpg" alt=""> </figure>';
echo '<h5><span>03</span> August</h5>';
echo '<p> Lorem ipsum dolor amet, consectetuer adipiscing elitom nonummy nibh euismod tincidunt ut laoreet dolore magna.';
echo '</div>';
echo '</div>';
echo '</article>';
echo '</div>';
echo '</section>';
echo '<!-- Footer -->';
echo '<footer>';
echo '<div class="copyright"> designed by saroj dhakal<a target="_blank" href="#/"></a> </div>';
echo '<ul class="social-list">';
echo '<li><a href="#"><img src="images/soc-icon-1.png" alt=""></a></li>';
echo '<li><a href="#"><img src="images/soc-icon-2.png" alt=""></a></li>';
echo '<li><a href="#"><img src="images/soc-icon-3.png" alt=""></a></li>';
echo '</ul>';
echo '</footer>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>