<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Fun Olympic</title>';
echo '<meta charset="utf-8">';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<link rel="stylesheet" href="css/match.css">';
echo '<script src="js/jquery-1.7.1.min.js"></script>';
echo '<script src="js/superfish.js"></script>';
echo '<script src="js/jquery.easing.1.3.js"></script>';
echo '<script src="js/tms-0.4.1.js"></script>';
echo '<script src="js/slider.js"></script>';
echo '<!--[if lt IE 9]>';
echo '<script src="js/html5.js"></script>';
echo '<link rel="stylesheet" href="css/ie.css">';
echo '<![endif]-->';
echo '</head>';
echo '<body>';
echo '<div class="main-indents">';
echo '<div class="main">';
echo '<!-- Header -->';
echo '<header>';
echo '<h1 class="logo"><a href="index.html">Fun olympic</a></h1>';
echo '<nav>';
echo '<ul class="sf-menu">';
echo '';
echo '<li><a href="about.html">About</a></li>';
echo '<li> <a href="Live Streaming.html">Live Streaaming</a>';
echo '<ul>';
echo '<li><a href="Live Streaming.html">Football</a></li>';
echo '<li><a href="Live Streaming.html">Basket Ball</a></li>';
echo '<li> <a href="Live Streaming.html">Circket</a></li>';
echo '<li><a href="Live Streaming.html">Cycling</a></li>';
echo '<li><a href="Live Streaming.html">More Games</a></li>';
echo '</ul>';
echo '</li>';
echo '<li><a href="Blog.html">Blog</a></li>';
echo '<li><a href="gallery.html">Galarry</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '<li><a href="user-registration.php">Signup/login</a>';
echo '<ul>';
echo '<li><a href="login.php">Admin Login</a></li>';
echo '<li><a href="login.php">User Login</a></li>';
echo '</ul>';
echo '</li>';
echo '</ul>';
echo '</nav>';
echo '<div class="clear"></div>';
echo '</header>';
echo '<section class="content-info">';
echo '<div class="container paddings-mini">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<table class="table-striped table-responsive table-hover result-point">';
echo '<h1>Match table</h1>';
echo '<thead class="point-table-head">';
echo '<tr>';
echo '<th class="text-left">No</th>';
echo '<th class="text-left">Teams</th>';
echo '<th class="text-center"> point</th>';
echo '<th class="text-center"> point</th>';
echo '<th class="text-center"> point</th>';
echo '<th class="text-center"> point</th>';
echo '<th class="text-center"> point</th>';
echo '<th class="text-center"> point</th>';
echo '<th class="text-center"> point</th>';
echo '';
echo '';
echo '';
echo '';
echo '</tr>';
echo '</thead>';
echo '<tbody class="text-center">';
echo '<tr>';
echo '<td class="text-left number">1 <i class="fa fa-caret-up" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://www.winwin.com/sites/default/files/styles/focal_point_scale_small_80x80/public/Al%20Hilal%20SCSC%20-%204378.png?h=55541bb6&itok=YbsJJ1dW" alt="Brazil"><span>الهلال</span> </td>';
echo '<td>10</td>';
echo '<td>7</td>';
echo '<td>2</td>';
echo '<td>19</td>';
echo '<td>9</td>';
echo '<td>+10</td>';
echo '<td>23</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">2 <i class="fa fa-caret-up" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://www.winwin.com/sites/default/files/styles/focal_point_scale_small_80x80/public/Al%20Nasr%20SCSC%20-%201548.png?h=55541bb6&itok=oFs1euKP" alt="Brazil"><span>النصر</span> </td>';
echo '<td>9</td>';
echo '<td>7</td>';
echo '<td>1</td>';
echo '<td>15</td>';
echo '<td>7</td>';
echo '<td>+8</td>';
echo '<td>22</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">3 <i class="fa fa-caret-up" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/argentina.png" alt="Argentina"><span>Argentina</span> </td>';
echo '<td>38</td>';
echo '<td>22</td>';
echo '<td>9</td>';
echo '<td>71</td>';
echo '<td>36</td>';
echo '<td>+35</td>';
echo '<td>75</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">4<i class="fa fa-caret-down" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/japan.png" alt="Japan"><span>Japan</span> </td>';
echo '<td>38</td>';
echo '<td>20</td>';
echo '<td>10</td>';
echo '<td>62</td>';
echo '<td>37</td>';
echo '<td>+25</td>';
echo '<td>70</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">5 <i class="fa fa-caret-up" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/flag.png" alt="Senegal"><span>Senegal</span> </td>';
echo '<td>38</td>';
echo '<td>19</td>';
echo '<td>12</td>';
echo '<td>58</td>';
echo '<td>53</td>';
echo '<td>+5</td>';
echo '<td>64</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">6<i class="fa fa-caret-down" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/poland.png" alt="Poland"><span>Poland</span> </td>';
echo '<td>38</td>';
echo '<td>18</td>';
echo '<td>12</td>';
echo '<td>52</td>';
echo '<td>48</td>';
echo '<td>+4</td>';
echo '<td>62</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">7<i class="fa fa-caret-down" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/russian-federation.png" alt="Russia"><span>Russia</span> </td>';
echo '<td>38</td>';
echo '<td>18</td>';
echo '<td>14</td>';
echo '<td>54</td>';
echo '<td>33</td>';
echo '<td>+21</td>';
echo '<td>60</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">8<i class="fa fa-caret-up" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/iran.png" alt="Iran"><span>Iran</span> </td>';
echo '<td>38</td>';
echo '<td>12</td>';
echo '<td>11</td>';
echo '<td>15</td>';
echo '<td>48</td>';
echo '<td>50</td>';
echo '<td>47</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">9 <i class="fa fa-circle" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/spain.png" alt="Spain"><span>Spain</span> </td>';
echo '<td>38</td>';
echo '<td>26</td>';
echo '<td>9</td>';
echo '<td>73</td>';
echo '<td>32</td>';
echo '<td>+41</td>';
echo '<td>87</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="text-left number">10<i class="fa fa-circle" aria-hidden="true"></i></td>';
echo '<td class="text-left"> <img src="https://img.icons8.com/color/48/000000/france.png" alt="France"><span>France</span> </td>';
echo '<td>38</td>';
echo '<td>24</td>';
echo '<td>7</td>';
echo '<td>83</td>';
echo '<td>38</td>';
echo '<td>+45</td>';
echo '<td>79</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Footer -->';
echo '<footer>';
echo '<div class="copyright"> designed by saroj dhakal<a target="_blank" href="#/"></a> </div>';
echo '<ul class="social-list">';
echo '<li><a href="#"><img src="images/soc-icon-1.png" alt=""></a></li>';
echo '<li><a href="#"><img src="images/soc-icon-2.png" alt=""></a></li>';
echo '<li><a href="#"><img src="images/soc-icon-3.png" alt=""></a></li>';
echo '</ul>';
echo '</footer>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>